[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/api/*"
  to = "https://api.soulseerpsychics.online/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
